[package]
name = "hidd"
version = "0.1.0"
edition = "2021"

[dependencies]
wry = "0.46.3"
tao = "0.30.3"
windows = { version = "0.48", features = [
    "Win32_Foundation", 
    "Win32_UI_WindowsAndMessaging"
]}